reload:
  name: "Reload"
  description: Reload localtuya and reconnect to all devices.

set_dp:
  name: "Set DP Value"
  description: Change the value of a datapoint (DP)
  fields:
    device_id:
      name: "Device ID"
      description: Device ID of device to change datapoint value for
      example: 11100118278aab4de001
    dp:
      name: "DP"
      description: Target DP, Datapoint index
      example: 1
    value:
      name: "Value"
      description: New value to set
      example: False
